"""initial schema

Revision ID: e3a2cf0b6051
Revises:
Create Date: 2026-04-03 13:48:23.150738

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e3a2cf0b6051"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
